### ISSUE TITLE
kdt.item.add大量上传时失败，报错：undefined:1 <!DOCTYPE html>

### ISSUE THREAD

**Issue by idisblueflash** [rayqian/youzan-sdk#2]
需求：需要用kdt.item.add上传262个商品
## 尝试1:

```
items.forEach(function(item){
   sdk.post('kdt.item.add', item['data'], {images: item.images}).then(function(data){
       console.log('uploaded.');
   });
});
```

**报错**，undefined:1。此时，已经上传100多商品，console.log出来只有30多条。

推测是因为node并发太多，导致。
## 尝试2:

用递归方法，逐个商品上传。等前个商品上传后，再上传下一个。
**报错**，undefined:1 或者无报错推出。每次上传商品数量都不同。
## 目前解法：

要自己记录已上传商品，然后多次运行上传脚本。
### 具体报错：

```
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/Users/fox/Documents/yunnong/transfer2youzan/node_modules/youzan-sdk/index.js:68:29)
    at Request.self.callback (/Users/fox/Documents/yunnong/transfer2youzan/node_modules/request/request.js:187:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/Users/fox/Documents/yunnong/transfer2youzan/node_modules/request/request.js:1048:10)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/Users/fox/Documents/yunnong/transfer2youzan/node_modules/request/request.js:969:12)
    at emitNone (events.js:85:20)
```

**Comment by idisblueflash** [comment]
上传商品过程中发现，貌似当上传图片images格式为png时，会导致上面的错误。

**Comment by rayqian** [comment]
@idisblueflash 报错的原因是图片问题？

**Comment by idisblueflash** [comment]
目前看是这样。貌似不支持png格式的图片，当我把png导出成jpg，就ok了。

**Comment by idisblueflash** [comment]
已经修改好了么？看到你close掉了。

**Comment by rayqian** [comment]
@idisblueflash 应该没有，我建议你去官网论坛提问，这个我也无能为力
